### PR TITLE
Breaking change: V1

### PR DESCRIPTION
**Pull request by luke-hill**
So I'd like to standardise this library a bit more. Given the changes recently rubocop side, it seems perfect to do it here.

I've included everything that I'm almost certain is needed. But left out lots of other stuff I'd like to do.

This currently alters a couple of cop overrides where they were doubly overwritten. It's likely this will cause new offenses but it's a breaking change and I don't see that as a big issue.

I would also like to (Reviews / Agreement pending)
- [x] Remove the following cop ignores (Non-controversial I think)
  - Layout/EmptyLineAfterMagicComment
  - Style/SymbolArray
- [x] Remove the following cop ignores (Slightly controversial I think)
  - Style/DoubleNegation
- Add justification / reasoning comments to all other style overrides (If we know them), if not look into altering them / removing them. This concerns the following cops
  - [x] Style/MixinGrouping
  - [x] Layout/MultilineMethodCallIndentation
  - [ ] Lint/AmbiguousBlockAssociation
  - [x] Metrics/AbcSize
  - [ ] Naming/MemoizedInstanceVariableName
  - [ ] Naming/MethodParameterName
- [ ] Look into instead integrating rubocop-rails into the gem proper. I can do this if there is a desire to do this (I've done it before).
- [ ] Look into integrating rubocop-rspec into the gem proper. This may allow us to remove a few more overrides (Also some of the spec overrides can probably go).

### CODE REVIEW

**Comment by luke-hill** [comment]
@mrdaniellewis I don't know who else would be worth reviewing this from your side / elsewhere in CA. Maybe let me know if I've missed anyone?

**Comment by rdsngit** [comment]
> @mrdaniellewis I don't know who else would be worth reviewing this from your side / elsewhere in CA. Maybe let me know if I've missed anyone?

@luke-hill I've added @cyeet to this review too as he has worked on the rubocop updates in casebook recently and might be aware of how this could affect the casebook codebase

**Review by cyeet — APPROVED** [review]
I think it should be fine. LGTM

**Comment by luke-hill** [comment]
So I've done the first check-mark (Remove non-controversial ones). So next step (Also pushed in), is removing the slightly more controversial one. DoubleNegation.

So in 99% of situations a non-nil check will suffice. The only single object this fails on is an explicit `false` object. However in these conditions we should be able to either pass them into something truthy or falsey, or question why we need the verbose value.

**Review by rdsngit — APPROVED** [review]
LGTM

**Review by mrdaniellewis — APPROVED** [review]
Looks good to me.  Difficult to know the impact to we run it on the code base

**Comment by luke-hill** [comment]
Whilst controversial. It feels good that in v1 there will be "some" impact, as it is a breaking change.

As always with rubocop. Local overrides can be done. What I'd argue is, use rubocop as a stick for change, and don't have all these overrides. I predict (Before my time), the reason for many of these is its easier to tell it to go away than fix poor code e.t.c.

I've fixed / documented up most. I'd like to tackle all bar the last 2 points in v1 (The other two can wait for another rainy day, maybe a v2>?)

**Comment by luke-hill** [comment]
I've marked on there what stuff to cull / fix up next. But will leave that to v2 and take the notable amount of wins now as it's had a load of approvals.

Can revisit this later down the line if/when we decide to update this more.

**Pull request merged**
