### PR TITLE
Feature/v3 removals

### PR DESCRIPTION
**Pull request by luke-hill**
Began to tackle some of the v3 removals. Some were easy, some required further research.

I've also not tackled some as I'm a bit at a loss to "why" they're there.

Any thoughts on removing other parts feel free to chirp up

### CODE REVIEW

**Review by rdsngit — APPROVED** [review]
looks good

**Comment by luke-hill** [comment]
I was looking into this cop, and it seems a bit odd. https://github.com/citizensadvice/citizens-advice-style-ruby/pull/21/files#diff-e5b4411416ca0f0d7c2372c297bdb99069c18746ed8433e1c955545c667a9b24L45

I always thought the best way was just to write them as `has_many` or `has_one` but I've not used Rails much recently, so I'm guessing this is something that is now advocated?

**Comment by mrdaniellewis** [comment]
I think it is a good rule to be enabled.  It makes you think about the model a bit more and what you want to happen when stuff gets deleted.

We haven't done this in Casebook, but we use foreign keys so it is mostly `restrict_with_exception`

**Comment by luke-hill** [comment]
Cheers for that. I'll enable it. I'll look into the other ones I marked TBD for v3 next week, unless you know whether they're good or bad.

**Comment by mrdaniellewis** [comment]
I like to exclude `Rails/SkipsModelValidations` on specs, also on `db/migrate/*`.

Related: I used this on this project https://github.com/citizensadvice/breathing-space-api-mock/blob/main/.rubocop.yml

But I didn't use the Rails rules from here.  I think it had some exclusions I didn't like on the migrations.

I also added rubocop-rspec, which was useful, but some of it is a bit heavy handed.

**Pull request merged**
